CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  article_slug VARCHAR(190) NOT NULL,
  service_name VARCHAR(190) NOT NULL,
  business_type VARCHAR(100) NOT NULL,
  company_name VARCHAR(190) DEFAULT NULL,
  industry VARCHAR(100) NOT NULL,
  prefecture VARCHAR(50) NOT NULL,
  usage_period VARCHAR(50) NOT NULL,
  usage_status VARCHAR(50) NOT NULL,
  amount_range VARCHAR(50) NOT NULL,
  completed_online VARCHAR(10) NOT NULL,
  reuse_intent VARCHAR(50) NOT NULL,
  issues_resolved TEXT NOT NULL,
  recommend_for TEXT DEFAULT NULL,
  answers_json JSON NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  submitted_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_reviews_article_slug (article_slug),
  KEY idx_reviews_status (status),
  KEY idx_reviews_ip_created_at (ip_address, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
